# Generated by Django 5.0 on 2024-04-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(default=123),
            preserve_default=False,
        ),
    ]
