# Generated by Django 5.0 on 2024-04-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProjectApp', '0002_film_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
