# Generated by Django 5.0 on 2024-04-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProjectApp', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
